### ISSUE TITLE
After installing package the included clientlib is not loaded

### ISSUE THREAD

**Issue by bjorns** [OlsonDigital/aem-groovy-console#53]
After following the installation instructions I the console is not fully visible. This seems to be because the clientlib at /etc/groovyconsole/clientlibs is not found/loaded. If I copy the node /etc/groovyconsole/clientlibs to /etc/clientlibs/groovyconsole the console shows up in all it's glory again.

![screen shot 2017-02-07 at 4 44 11 pm](https://cloud.githubusercontent.com/assets/231258/22713026/d6646242-ed54-11e6-931b-c7e8c9fed28e.png)

Environment:
AEM 6.2
Chrome
macOS

**Comment by lykorian** [comment]
Fixed in 10.1.0... thanks!

**Comment by bjorns** [comment]
Cool, thanks
