### ISSUE TITLE
Global methods not generally available

### ISSUE THREAD

**Issue by bjorns** [OlsonDigital/aem-groovy-console#56]
I'm trying to build a generic set of helper classes, but I have trouble accessing the "global" methods from withing a class, here's an example for println:

    class MyClass {
        def sayHello() {
            println "Hello world"
        }
    }

    inst = new MyClass()
    inst.sayHello()
    return 0`

Same thing with getNode()

    class Helper{
        def findNode(String path) {
            return getPath(path)
        }
    }
    
    inst = new Helper()
    println inst.findNode("/content/dam")
    return 0

**Comment by lykorian** [comment]
See here for details.

https://stackoverflow.com/questions/15619216/groovy-scope-how-to-access-script-variable-in-a-method

You can pass the `binding` object to your class in the following manner:

```
import groovy.transform.TupleConstructor

@TupleConstructor
class MyClass {
    
    Binding binding
    
    def sayHello() {
        binding.out.println "Hello world"
    }
}

inst = new MyClass(binding)
inst.sayHello()
```
```
import groovy.transform.TupleConstructor

@TupleConstructor
class Helper{
    
    def script
    
    def findNode(String path) {
        script.getNode(path)
    }
}

inst = new Helper(this)

println inst.findNode("/content/dam")
```
