### ISSUE TITLE
Failure if script does not return value

### ISSUE THREAD

**Issue by bjorns** [OlsonDigital/aem-groovy-console#57]
The following script gives me a failure

    println "Hello, world!"

Unless the script returns a value it is not executed.

    println "Hello, world!"
    return 0

Shouldn't this at least be documented?

**Comment by lykorian** [comment]
What version of the console are you using?

**Comment by bjorns** [comment]
Right, sorry about that. It's groovy console 10.1.0 on an AEM 6.2 SP1
