### ISSUE TITLE
console 10.1.1 not working on 6.3 beta

### ISSUE THREAD

**Issue by santiagozky** [OlsonDigital/aem-groovy-console#58]
the groovy console bundle wont start in AEM version 6.3 beta.
the bundle imports: com.day.cq.mailer,version=[5.9,6) -- Cannot be resolved.
Current beta exports the package in version 6.0.0.
Would be nice if this can be updated before official release to ensure smooth upgrades.

**Comment by lykorian** [comment]
Thanks Santiago.  I'm still working on getting a new development snapshot working for 6.3.

**Comment by lykorian** [comment]
See `develop` branch for latest snapshot.

**Comment by santiagozky** [comment]
Thanks @lykorian ! it seems to work fine.
