### ISSUE TITLE
"Download the console package" link broken in README

### ISSUE THREAD

**Issue by jakegarelick** [OlsonDigital/aem-groovy-console#60]
I think the title describes the problem well enough. I would've done a PR to fix, but the releases section confuses me.

While I have your attention, what is the difference between the standard aem groovy console and the aem groovy console "exclude groovy bundle"?

**Comment by lykorian** [comment]
The "exclude groovy bundle" profile omits the groovy-all OSGi bundle from the assembled package.  This is recommended if you have another app deployed to your AEM instance that supplies its own version of the groovy-all bundle and don't want to introduce any potential conflicts.
