### ISSUE TITLE
Groovy Console 10.1.1 and AEM6.2: Required script resource could not be located: head.js

### ISSUE THREAD

**Issue by olimination** [OlsonDigital/aem-groovy-console#61]
If I install aem-groovy-console 10.1.1 in plain AEM6.2 and open aferward the page /etc/groovyconsole.html it throws following exception:

`..SightlyUseException: Required script resource could not be located: head.js...`

After some research I've found this forum post:
https://forums.adobe.com/thread/2333338

which seems to be related to this issue.

As a workaround I have patched the `head.html` and the `headlibs.html` files, see here my branch with the fix: https://github.com/OlsonDigital/aem-groovy-console/compare/master...olimination:aem62-headjs-script-not-found?expand=1

Should I create a Pull Request for it or do you have any other fix for this?

**Comment by lykorian** [comment]
Go ahead and open a pull request - thanks!
