### ISSUE TITLE
Audit records now saved on user but not shown in groovyconsole.html

### ISSUE THREAD

**Issue by Strat1987** [OlsonDigital/aem-groovy-console#65]
Dear,

Upgrading to version 11.0.0 we noticed the audit nodes are now saved in a tree structure that begins with the user id from the session.

We perform our patches with a custom system user, so the audit logs are not stored in audit/admin but in audit/ourCustomUser. But these audit records are not being displayed in the History panel of /etc/groovyconsole.html.

As this is a system user, we cannot login with this user.

**Comment by lykorian** [comment]
See the updated README for details on the new OSGi configuration property for this.  After enabling that option, you will see audit records for all users in the History.

**Comment by Strat1987** [comment]
Thanks a lot for adding this configuration! We'll be sure to check this ASAP
