### ISSUE TITLE
Groovy console is installed before the primary types are available

### ISSUE THREAD

**Issue by royteeuwen** [OlsonDigital/aem-groovy-console#67]
Hey,

I have the following setup:

The AEM jars gets extracted with java -jar aem.jar -unpack
The install folder is made in crx-quickstart
All my dependencies are put in the install folder so that they get installed on startup

The problem that groovy console is having is that no dependency is set on AEM itself, so the content gets installed before even de cq-content is available, producing following errors:

13.09.2017 12:06:59.763 ERROR [OsgiInstallerImpl] org.apache.jackrabbit.vault.fs.io.Importer E (javax.jcr.nodetype.NoSuchNodeTypeException: Node type cq:Page does not exist)

A dependency should be set on cq-content to make sure that the bundle is installed in the right order

**Comment by royteeuwen** [comment]
@lykorian have time to look at this one maybe? I'd rather not make a custom forked build if not needed ;)

**Comment by lykorian** [comment]
Hi Roy,

I merged your change into the "develop" branch.

Thanks for the update,

Mark

**Comment by royteeuwen** [comment]
Hey Mark,

Yea sorry, it seems that the the default merge branch is master, didn't notice! Thanks for merging

Greets,
Roy

**Comment by royteeuwen** [comment]
Hey @lykorian ,

Could you maybe make a release for this?

Thanks!
Roy

**Comment by lykorian** [comment]
@royteeuwen sorry for the long delay - this is done (11.0.2)

**Comment by royteeuwen** [comment]
Perfect, thanks!!
