### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke method recurse() on null object

### ISSUE THREAD

**Issue by chicago60614** [OlsonDigital/aem-groovy-console#70]
I just installed the Groovy 11.0 package to my local instance of AEM 6.3.    Most of the sample scripts don't work.  Scripts that worked on my existing CQ 5.5 / Groovy 3 instances don't work in  AEM6.3/Groovy11.0. 

getPage should work but does not.

Any suggestions? 

getPage("/content").recurse { page ->
}

java.lang.NullPointerException: Cannot invoke method recurse() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)

![2017-12-17_14-12-17](https://user-images.githubusercontent.com/34606448/34083332-5f79dc9e-e334-11e7-9f2a-baf76b45c157.png)

**Comment by toniedzwiedz** [comment]
@chicago60614 I haven't used these versions yet but I think the Groovy Console uses `PageManager` internally. If it's returning `null`, it's probably due to the structure of your content. I'd start by checking if the `/content` node exists and if it is an actual Page. What's its `jcr:primaryType`?

**Comment by lykorian** [comment]
`/content` is a `sling:OrderedFolder` node, not a page, so that is why the `getPage` method is returning null.  You can use the `getNode` method, however, and call `recurse()` on the node instead.

I am in the process of updating the sample scripts - most of them depended on Geometrixx.

**Comment by lykorian** [comment]
See release `11.3.0` with updated sample scripts.
