### ISSUE TITLE
Is there a way to stop a script you started executing before it finishes?

### ISSUE THREAD

**Issue by Strat1987** [OlsonDigital/aem-groovy-console#71]
Dear,

Is there a way to stop a script from executing once it has started and before it finishes?

Kind regards
Bert

**Comment by lykorian** [comment]
Not reliably - this would require killing the thread and could have unpredictable consequences.

**Comment by Strat1987** [comment]
We sometimes have scripts that take a long time to run, which we might want to interrupt.
The workaround we use now, is to uninstall the package in package manager ... but that seems a bit drastic

**Comment by tadijam64** [comment]
> We sometimes have scripts that take a long time to run, which we might want to interrupt.
> The workaround we use now, is to uninstall the package in package manager ... but that seems a bit drastic

I don't think this would solve the issue, it is likely that your script will still run in the background once you've deleted the package. It is compiled to the Java Bytecode, so you would need to kill the java process or stop the thread to make sure it is stopped.

Can someone confirm this?
