### ISSUE TITLE
AEM 6.4 Compatibility?

### ISSUE THREAD

**Issue by toniedzwiedz** [OlsonDigital/aem-groovy-console#73]
Hello,

I'm working on an AEM 6.4 project. Do you happen to have a release date set for a production-ready release of version 12.0.0?

How stable is the Snapshot?

**Comment by lykorian** [comment]
The goal is to have a proper release within the next two weeks.  However, the snapshot is pretty stable.  I do not anticipate any significant changes to it before the release.  Thanks!

**Comment by toniedzwiedz** [comment]
@lykorian I've been using the snapshot and it seems to work properly. I'm inclined to install it across more than my local environment but I'd rather hold off for a couple of days if it means being able to use the official version. How's the release coming along? Is it expected to happen over the next few days?

**Comment by ebernard** [comment]
I'm planning a migration to 6.4 as well and the groovy console is the last dependency that's still holding me back. I too would rather use an official version.

**Comment by lykorian** [comment]
Thanks for your patience.  Enjoy.

**Comment by toniedzwiedz** [comment]
Thanks for the release!
